// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/control_plane/v1/inter_service.proto

package control_plane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InterService_UpdateDRKey_FullMethodName = "/proto.control_plane.v1.InterService/UpdateDRKey"
)

// InterServiceClient is the client API for InterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterServiceClient interface {
	// method to add drkey to database
	UpdateDRKey(ctx context.Context, in *UpdateDRKeyRequest, opts ...grpc.CallOption) (*UpdateDRKeyResponse, error)
}

type interServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterServiceClient(cc grpc.ClientConnInterface) InterServiceClient {
	return &interServiceClient{cc}
}

func (c *interServiceClient) UpdateDRKey(ctx context.Context, in *UpdateDRKeyRequest, opts ...grpc.CallOption) (*UpdateDRKeyResponse, error) {
	out := new(UpdateDRKeyResponse)
	err := c.cc.Invoke(ctx, InterService_UpdateDRKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterServiceServer is the server API for InterService service.
// All implementations must embed UnimplementedInterServiceServer
// for forward compatibility
type InterServiceServer interface {
	// method to add drkey to database
	UpdateDRKey(context.Context, *UpdateDRKeyRequest) (*UpdateDRKeyResponse, error)
	mustEmbedUnimplementedInterServiceServer()
}

// UnimplementedInterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInterServiceServer struct {
}

func (UnimplementedInterServiceServer) UpdateDRKey(context.Context, *UpdateDRKeyRequest) (*UpdateDRKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDRKey not implemented")
}
func (UnimplementedInterServiceServer) mustEmbedUnimplementedInterServiceServer() {}

// UnsafeInterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterServiceServer will
// result in compilation errors.
type UnsafeInterServiceServer interface {
	mustEmbedUnimplementedInterServiceServer()
}

func RegisterInterServiceServer(s grpc.ServiceRegistrar, srv InterServiceServer) {
	s.RegisterService(&InterService_ServiceDesc, srv)
}

func _InterService_UpdateDRKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDRKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterServiceServer).UpdateDRKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterService_UpdateDRKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterServiceServer).UpdateDRKey(ctx, req.(*UpdateDRKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterService_ServiceDesc is the grpc.ServiceDesc for InterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.control_plane.v1.InterService",
	HandlerType: (*InterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDRKey",
			Handler:    _InterService_UpdateDRKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane/v1/inter_service.proto",
}
